config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :receptionists
  resources :doctors
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor
end  

app/models/receptionist.rb
class Receptionist < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def patient_registration_chart
    @doctor = Doctor.find(params[:id])
    @patients_registered_by_day = @doctor.patients.group_by_day(:created_at).count
    render json: @patients_registered_by_day
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :require_login
  
    def index
      @patients = Patient.all
    end
  
    # Other CRUD actions...
  
  end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  before_action :require_login

  def index
    @receptionists = Receptionist.all
  end

  def show
    @receptionist = Receptionist.find(params[:id])
  end

  def new
    @receptionist = Receptionist.new
  end

  def create
    @receptionist = Receptionist.new(receptionist_params)
    if @receptionist.save
      redirect_to @receptionist, notice: 'Receptionist was successfully created.'
    else
      render :new
    end
  end

  def edit
    @receptionist = Receptionist.find(params[:id])
  end

  def update
    @receptionist = Receptionist.find(params[:id])
    if @receptionist.update(receptionist_params)
      redirect_to @receptionist, notice: 'Receptionist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @receptionist = Receptionist.find(params[:id])
    @receptionist.destroy
    redirect_to receptionists_url, notice: 'Receptionist was successfully destroyed.'
  end

  private

  def receptionist_params
    params.require(:receptionist).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
    <% if doctor.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>
  
        <ul>
          <% doctor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
  
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
  
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/doctors/index.html.erb
<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.email %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Receptionist Doctor Portal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<nav>
  <% if logged_in? %>
    <%= link_to 'Home', root_path %>
    <%= link_to 'Receptionists', receptionists_path %>
    <%= link_to 'Doctors', doctors_path %>
    <%= link_to 'Patients', patients_path %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Login', login_path %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
  
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age %>
    </
  

app/views/patients/index.html.erb
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/receptionists/_form.html.erb
<%= form_with(model: receptionist, local: true) do |form| %>
    <% if receptionist.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(receptionist.errors.count, "error") %> prohibited this receptionist from being saved:</h2>
  
        <ul>
          <% receptionist.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
  
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
  
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/receptionists/index.html.erb
<h1>Receptionists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receptionists.each do |receptionist| %>
      <tr>
        <td><%= receptionist.name %></td>
        <td><%= receptionist.email %></td>
        <td><%= link_to 'Show', receptionist %></td>
        <td><%= link_to 'Edit', edit_receptionist_path(receptionist) %></td>
        <td><%= link_to 'Destroy', receptionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receptionist', new_receptionist_path %>

app/views/receptionists/new.html.erb
<h1>New Receptionist</h1>

<%= render 'form', receptionist: @receptionist %>

<%= link_to 'Back', receptionists_path %>